### ISSUE TITLE
[Views][Admin] Bulk upload of Resporg IDs

### ISSUE THREAD

**Issue by gaurav-teliax** [tfxc/issues#28]
We need to add a new feature in TFXC where the `Admin` user right now and in the future, the Resporgs through their accounts are able to bulk upload their ROIDs. In the first phase, we will be uploading functionality in the admin section. 
The upload will happen by the `Admin` user uploading a CSV and then the TFXC views processing the CSV to create `unconfirmed`  ROIDs in their account. 
The CSV file will have the following header fields:
1. `Resporg ID` # => The actual ROID
1. `Name` # => User friendly identifier
1. `Origin SIP Trunk IPs` # => originating ro ips
1. `Terminating SIP Trunk IPs` # => term ro ips
1. `Default Sell Rate` 
1. `Default Ceiling Rate`
1. `All Traffic` # => Y/N
1. `Receive CIC` # => Y/N

In addition, the Admin will have a dropdown to select the Resporg they want to upload the RO for.

_The steps that the Resporg needs to perform once a ROID has been added to their account remains the same like getting an email confirmation to the primary and secondary contacts and then the RO verifying individual ROIDs one at a time. 
This is just making Resporgs easy to bulk create ROIDs instead going into the browser and adding the ROIDs 1 at a time.
Why do we need this feature, there is a customer called Kall8 that hasa 70+ ROIDs and it will become ver cumbersome to add'em 1 at a time._

Please note that the functionality is only to `create` ROIDs. Meaning if there is duplicate entries in the CSV file that they have an existing ROID in the system the entry will be ignored be it for their own Resporg or mistakenly someone else's Resporg. No `updates` or `deletes`.

Q: How do we handle the IP assignment if these ROIDs are on the originating side. We have deactivated the auto-assignment IP feature. We will need to handle that manually.

**Comment by CarlsBad505** [comment]
Notes to self. Test / Review the following:

- Frontend UI
- CarrierWave
- GCP Storage
- Sidekiq --> mount the dashboard and make sure the job gets queued in, ran, then exits successfully asynchronously.
- Rspecs (currently failing inside of docker due to a permissions issue... at `public/uploads`... figure it out)

**Comment by CarlsBad505** [comment]
3 failing `rspecs` for the model, check it out. All controller specs passing.

**Comment by suraiyarahmet** [comment]
The following is a step-by-step use case and its outcome:

1. Upload a csv file with the following values (note that REN16 includes more than one IP in **Origin SIP Trunk Ips** column, but is not listed within double quotes.

![Screen Shot 2020-08-05 at 12.55.17 PM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/ea0469f1-a160-4183-b0cc-1249c34395bc)

![Screen Shot 2020-08-05 at 12.58.18 PM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/f9cabe8c-2d08-4e2f-97cd-4dcb255d986f)![Screen Shot 2020-08-05 at 12.58.34 PM.png]

![Screen Shot 2020-08-05 at 12.58.34 PM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/a261da96-3245-4f2a-acaf-c9dfac141f7d)

2. Go to Listing RespOrg IDs page for account (e..g Listing RespOrg IDs for Teliax, Inc.) and **Confirm Rate** for each resporg. 

![Screen Shot 2020-08-05 at 1.06.11 PM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/9c4cecf6-a41a-4770-9f7f-edd27c9750f3)

3.  Go to Resp Org IDs List page (select account number from account list page e.g. select Account # 3 in order to be directed to Teliax, Inc.'s Resp Org IDs List page)

![Screen Shot 2020-08-05 at 1.08.45 PM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/51ba75d7-5258-4c24-8c52-41052ade201d)

4. Select **Edit icon** from Actions section of list of newly uploaded resporg (e.g. REN16). Note that **Originating Trunk Group IPs** have been inheriting correctly. This was the ResOrg that did not include double quotation marks when adding values in csv. Also note that in **Terminating Trunk Groups section**, IP was inherited with double quotes and brackets.

![Screen Shot 2020-08-05 at 1.12.46 PM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/0d93bccf-acad-40ee-976b-bffc18ebeee2)

![Screen Shot 2020-08-05 at 1.13.53 PM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/70d70147-3a57-44e2-8c86-2e16d206f144)

- The following is an example of what the **Terminating Trunk Group IP(s)** should look like:

![Screen Shot 2020-08-05 at 1.14.25 PM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/c56a5dd1-7a49-40ff-9f48-e0bfda7cdfc3)

5. Select **Edit icon** for another newly uploaded resporg (e.g. REN15). Notice that in the **Originating SIP Trunk IP** section, the double quotes were inherited along with the IPs. Also note that in the **Terminating Trunk Group IP** section, that no SIP trunks are listed despite this being populated in the csv for REN15 (the value was '1.1.1.1'). 

![Screen Shot 2020-08-05 at 1.16.32 PM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/d3cadd70-156d-49ca-9488-02e765263ec1)

![Screen Shot 2020-08-05 at 1.16.36 PM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/71595744-4927-47dd-95c1-42b666b5c16a)

6. REN17 is a similar case. Notice how the **Terminating SIP Trunk Group IPs** are inherited.

![Screen Shot 2020-08-05 at 1.20.04 PM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/a47f6c4f-3607-4824-b45f-376f899d3eac)

![Screen Shot 2020-08-05 at 1.20.11 PM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/063c5ab8-48de-47ed-99f4-46157dc8a976)

**Comment by CarlsBad505** [comment]
Thanks Suraiya

1) Double quotes should not be used in `.xls` extensions, but should be explicitly used in `.csv` extensions.
2) Terminating IPs are now displayed and persisted. correctly to the DB.

![Screen Shot 2020-08-05 at 3.47.45 PM.png](https://images.zenhubusercontent.com/5eab2b9f1e31bd010da5e432/31591ce3-d566-4cf6-b773-3275922407ef)

![Screen Shot 2020-08-05 at 3.47.55 PM.png](https://images.zenhubusercontent.com/5eab2b9f1e31bd010da5e432/268a3c1f-b021-47e9-9174-2cc823649904)

**Comment by suraiyarahmet** [comment]
Approved. Tested both .csv and .xls per comment above and results did not inherit quotations. Terminating IP formatting looks good:

![Screen Shot 2020-08-10 at 9.50.54 AM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/29a21ee8-b0a7-495d-9680-db6bc0a191bc)

![Screen Shot 2020-08-10 at 9.51.34 AM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/04afc5d9-1830-4600-af0c-1b8e3f114fa6)

![Screen Shot 2020-08-10 at 9.52.08 AM.png](https://images.zenhubusercontent.com/5eab10c566f31d03bce1313f/02e15789-ad2b-4d69-950c-e744f45b7358)
