### ISSUE TITLE
Peering deal between Teliax & LogMeIn is not working

### ISSUE THREAD

**Issue by rshawnkeller** [tfxc/issues#40]
NEX99 launched a peering deal to LMI for .0025.  After several attempts, we finally got LMI and David A. on the phone for the peering launch.  Aaron did not receive the request.  It is however listed in NEX99 Individuale sell rate for all SX ROIDs at .0025.  LMI (Get Go Audio Acnt) has a ceiling rate of .003.  Currently majority of calls are not peering due to rate mismatch even though NEX99 sell rate is lower then LMI ceiling rate.  It is not due to uploaded (and outdated) LMI price protection as we have calls that peer when the Price Protection is lower and calls that are 503 Route Advanced when price protection is higher.  ASR is less then 40% when it should be 100%.  This is resulting is a loss of income for both Teliax and TFX.

**Comment by teliaxdavec** [comment]
I've got an update from TollFree.Exchange Support Team (Christy Belcher). Essentialy she's discovered that the discrepancy involves " an Originating ROID launches a peering deal for an amount that is LESS than the terminating resporgs ceiling rate, the deal does not show up in the deal center.  Clicking “accept” in the notification email does not populate the Terminating ROIDs Individual ceiling rate table.  This results in a non-Peered deal."

Full details from Christy below.

An individual case ticket has already been opened:  https://it.teliax.com/support/tickets/613 and is queued up in GitHub.
Backstory: Before there was automation, peering was manual
A Partner launches a deal via the RespOrg configuration pop-up (accessed by clicking edit (pencil) icon for appropriate ROID)



 If Partner is Sending traffic, they would click on the Individual Sell Rate tab. Choose the ROID you are launching the offer to from the dropdown, enter in the sell rate you are offering and click the “+” button to add to table of peering deals.
To accept the deal, the (in this scenario) Partner who is receiving the traffic would enter a corresponding rate in their “Individual ceiling rate” tab.
These two corresponding rates would create a “Peered” deal.
This becomes important in our hierarchy of Go, No Go, which is the logic used to determine a financial peering match. See below for hierarchy:
1. Peered Deal
2. Rate Protection
3. Ceiling Rate
If a “Peered” deal is not present, we then look to Rate Protection (uploaded rate deck for term ROID) then the ceiling rate. 
If an Individual ceiling rate is entered into the Originating RoIDs table, but a corresponding rate is not found in the Terminating ROIDs table, the system will not find a “Peered” deal.
Automation was implemented to foster communication between partners and make the addition of a peering rate to the Partner’s table(s) automatic.  This automation was facilitated by adding a “notify resporg” option to the peering tabs.  The notification email generated by checking this “notify resporg” option includes an “activate/accept” button.  In addition, an entry is created in the notified resporgs deal center.  Clicking the “activate” button in the notification email would automatically populate the accepting ROIDs peering table with the accepted rate and crate a “Peered” deal.  This is the expected behavior.
Current Behavior
If an Originating ROID launches a peering deal for an amount that is LESS than the terminating resporgs ceiling rate, the deal does not show up in the deal center.  Clicking “accept” in the notification email does not populate the Terminating ROIDs Individual ceiling rate table.  This results in a non-Peered deal.
If an Originating ROID launches a peering deal for an amount that is MORE than the terminating resporgs ceiling rate, the deal center will populate with the offer, but clicking the accept button within the notification email will not actually accept the deal (same as above).  This results in a non-peered deal.  Clicking the “Accept” button within the Deal Center will populate the terminating roids ceiling rate table.   This function is the same if the terminating Roid launches a deal.
Peered Deals result in a 95-100% ASR.
All launched deals (regardless of if they are launched by the Originating or Terminating ROID) should show up in the deal center when the “notify RespOrg” is checked. When “accept” button is clicked in the notification email, deal should be accepted and populated in the corresponding table.
Please let me know if you need additional background information or explanations.

**Comment by CarlsBad505** [comment]
Notes to Self:

Pay special attention to the method `reconcile_and_accept_rate!` in the `IndividualSellRate` class. 

- There is conditional logic. If the IndividualCeilingRate.rate of the terminating resporg paired with the originating resporg, in the peer deal, is less than pending_notification_sell_rate (AKA - the proposed rate in the deal), then we raise the IndividualCeilingRate of that terminating resporg to match this value. Otherwise, we leave it as was. And "as was" was either first or initialized. This is important... because we don't persist this record `IndividualCeilingRate` unless this conditional was met. What are the ramifications if we don't persist upon this conditional? Why wouldn't we persist no matter what, even on initialization of the record? It looks like this is partially related to user expectations to see an Individual Ceiling Rate... but we don't always persist it.

- To accept the deal, we must traverse a series of DB actions in one atomic transaction. This includes persisting and updating records to the `Rate` and `RateHistory` tables. Any complications will be exited or rescued, thereby returning from the atomic transaction with false and the acceptance cannot be completed.

**Comment by CarlsBad505** [comment]
Notes to Self:

Persistence of individual sell rate for NX99 -> SXC99 is in the database and has the correct attributes. Furthermore, the rate record for NX99 includes this in the `active_sell_rate` hash. This all looks solid.

However, when I go to look at the SXC99 rate record in the database, it does not have its peer NX99 in its `active_sell_hash`. Not only that, the associated individual ceiling rates returns empty array. Could this be the issue?

Next Steps - Try full cycle of creating a peering deal below the term ceiling rate, accept it, then `byebug` the transactions to ensure nothing broke during persistence. My guess is it won't based on what we've seen so far...

**Comment by CarlsBad505** [comment]
Notes to Self:

1) Do we know for sure that a missing individual sell rate record means that there is **not** a peered deal?

2) Investigate the conditional logic preventing persistence.

**Comment by CarlsBad505** [comment]
General Notes:

We've seen that the Resporg Account Ids `OMM02` and `OMM01` belonging to Resporg `West` (id #39) were peered with SXC01 `LogMeIn Audio` (id #41) at `created_at` January 29, 2019. More than 1.5 years ago. Whats especially interesting about this is that their peering deals `pending_notification_sell_rate` (AKA the rate proposed in the deal), was `0.0015`. Meanwhile, the `terminating_sip_trunk_ceiling_rate` (AKA the ceiling rate) for `SXC01` is `0.003`.

This is really interesting because the ceiling rate `0.003` is **not** less than the proposed rate `0.0015`. In other words, `0.003` < `0.0015` evaluates as false. We care about this because in the code, this means we do not persist / update a new `IndividualCeilingRate` between the two parties for `SXC01`.

But in this case specifically, we DO have `IndividualCeilingRates` in `SXC01` for both `OMM01` and `OMM02`. You can see these in the database, the respective row ids in the `IndividualCeilingRates` table are #137 and #146.

So how the heck did that happen, how was that possible? My theory here is that those peers were done manually in the past. Christy talked about how peering used to be more manual and the accepting / terminating resporg account id had to input their own ceiling rate.

It could be, that now that we rely on it being automated, this conditional we talked about above isn't doing what we need it to do. It appears that even though the proposed rate is LESS than the terminating resporg account id ceiling rate (proposed rate of 0.0015 is < ceiling rate of 0.003), a `IndividualCeilingRate` is still persisted to the database. Suggesting that this is how its supposed to be for a true peering to work properly. It appears that not having a `IndividualCeilingRate` record between the two parties is insufficient.

**Comment by CarlsBad505** [comment]
**Test:** Move persistence of the `IndividualCeilingRate` outside of the conditional and test locally to see if it works regardless if the proposed peer rate is higher or lower than the terminating resporg account id ceiling rate.

I'm more confident this should be the solution now, given what we know.

1) Change code
2) Fix affected rspecs (if any)

**Comment by CarlsBad505** [comment]
**Current Status:**

After speaking w/ Shaun Moore and Christy, it sounds like we may not want to change any of this code because it might be behaving the way it should. If the proposed rate is lower than the terminating resporg ceiling rate, we still don't do a direct peer `automatically` because some of that traffic could be coming from aggregators (aggregating various phone companies who own differing NPANXX). It protects the Resporgs, as we still still fall back to rate protection.

The terminating resporg can still accept the deal if they want manually by explicitly inputting an `IndividualCeilingRate` via the UI form.

All the while keeping in mind that proposed peer deal rates which are **above** the terminating resporg ceiling rate, does go through automation - automatically creating that `IndividualCeilingRate`.

**Comment by CarlsBad505** [comment]
Notes:

Today, had a meeting between TFX (Shaun + Christy) and David A. They understand and are on the same page. They are going to talk more about it and come back to us with action items. This investigation is now complete.
